# Generated by Django 2.1 on 2019-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YoutubeLink', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Youtube Link')),
                ('votes', models.IntegerField(default=0)),
                ('SongName', models.CharField(max_length=50)),
            ],
        ),
    ]
